Description: Store Github credentials in Secrets Manager

Parameters:

  GithubUsername:
    Type: String
    Description: Your Github username

  GithubTokenSecretName:
    Type: String
    Description: >-
      The name of a Secret in Secrets Manager that contains your Github
      username and Personal Access Token

  GithubUsernameKey:
    Type: String
    Description: >-
      The name of the JSON key in the Secret that contains your username

  GithubAccessTokenKey:
    Type: String
    Description: >-
      The name of the JSON key in the Secret that contains your
      Personal Access Token

Resources:

  GithubCodeBuildCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref GithubTokenSecretName
      Description: !Sub Github Personal Access Token for ${GithubUsername}
      SecretString: !Sub '{"${GithubUsernameKey}":"${GithubUsername}", "${GithubAccessTokenKey}": ""}'
